### PR TITLE
created a rating element

### PR DESCRIPTION
**Pull request by abdelhamiderrahmouni**
This is a rating element that enables the user to get the value of the rating, as well as passing the value they want and visualize it.
The user can also customize the icons.

The following is a preview of the element.

Recording 2023-10-18 231753

### CODE REVIEW

**Comment by abdelhamiderrahmouni** [comment]
Recording 2023-10-18 231753

**Comment by tnylea** [comment]
This is so good! I'll do some testing and then add it in.

**Comment by abdelhamiderrahmouni** [comment]
Thank you so much for the consideration i hope it is usefull

**Comment by tnylea** [comment]
Sorry for not merging this sooner. I'm merging in now and testing out and then I'll be sure to get it live.

Thanks for this component ;)

**Comment by abdelhamiderrahmouni** [comment]
😍 Thanks a lot for the merge @tnylea, i am super happy it was useful ❤️, and i can't wait to contribute more useful ones 👍

**Pull request merged**
